site_name: Pawleys Logic* Heraeus Electro-Nite Downloads and Documentation
site_url: https://pawleyslogic.com
theme:
  name: material
  palette:
    - scheme: default  # light mode
      primary: deep orange  # or custom below
      accent: orange




nav:
  - Home: index.md
  - SensorLab Steel (SLS):
      - SLS ProfiNet Output Register User Guide : instruments/sls/sls_output_register_pnet_cfg_guide.md
  - CasTmp Wireless E5 (CTWE5):
      - CTWE5 Add-On User Guide : instruments/HEN_CTWE5Parser_CLX34_UserGuide.md
  - Downloads : downloads/down_loads.md




      
      
features:
  - navigation.tabs




markdown_extensions:
  - admonition
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg






    
extra:
  include_cname: true

