site_name: Pawleys Logic* Heraeus Electro-Nite Downloads and Documentation
theme:
  name: material
  palette:
    primary: blue
    accent: light blue

nav:
  - Home: index.md
  - CasTmp Wireless E5 (CTWE5):
      - CTWE5 Add-On User Guide : instruments/HEN_CTWE5Parser_CLX34_UserGuide.md

